CREATE TRIGGER trg_Review_Delete
ON Store
AFTER DELETE
AS
BEGIN
    DELETE FROM Review WHERE ReviewStoreID IN (SELECT StoreID FROM DELETED);
END;

CREATE TRIGGER trg_Review_User_Delete
ON [User]
AFTER DELETE
AS
BEGIN
    DELETE FROM Review WHERE ReviewUserID IN (SELECT UserID FROM DELETED);
END;